CREATE OR REPLACE DATABASE COVID19_DB_COPY;
CREATE OR REPLACE SCHEMA COVID19_DB_COPY.PUBLIC;

-- MAKE MARKETPLACE DATABASE COPY (NEEDED FOR OPTIMIZATION TASKS AND SHARING DATABASE)
CREATE OR REPLACE TABLE COVID19_DB_COPY.PUBLIC.ECDC_GLOBAL AS
SELECT *
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.ECDC_GLOBAL;

SHOW TABLES IN SCHEMA COVID19_DB_COPY.PUBLIC;

SELECT COUNT(*) AS total_rows
FROM COVID19_DB_COPY.PUBLIC.ECDC_GLOBAL;
