SELECT *
FROM COVID19_DB_COPY.PUBLIC.ECDC_GLOBAL
MATCH_RECOGNIZE(
    PARTITION BY COUNTRY_REGION
    ORDER BY DATE
    MEASURES
        FIRST(DATE) AS wave_start_date,
        LAST(DATE) AS wave_end_date,
        SUM(CASES_SINCE_PREV_DAY) AS total_cases_in_wave,
        MAX(CASES_SINCE_PREV_DAY) AS peak_cases_in_wave
    ONE ROW PER MATCH
    AFTER MATCH SKIP PAST LAST ROW
    PATTERN (UP+ PLATEAU* DOWN+)
    DEFINE
        UP AS CASES_SINCE_PREV_DAY > LAG(CASES_SINCE_PREV_DAY),
        PLATEAU AS CASES_SINCE_PREV_DAY = LAG(CASES_SINCE_PREV_DAY),
        DOWN AS CASES_SINCE_PREV_DAY < LAG(CASES_SINCE_PREV_DAY)
);
