-- Switch to ACCOUNTADMIN role
USE ROLE ACCOUNTADMIN;

-- Create the resource monitor
CREATE RESOURCE MONITOR COVID_TRIAL_RM
  WITH CREDIT_QUOTA = 100
  FREQUENCY = MONTHLY
  START_TIME = CURRENT_TIMESTAMP
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 85 PERCENT DO SUSPEND
    ON 95 PERCENT DO SUSPEND_IMMEDIATE;

-- Assign the monitor to the warehouse
ALTER WAREHOUSE COMPUTE_WH
  SET RESOURCE_MONITOR = COVID_TRIAL_RM;
